default:
  models:
    Client: read
    Campaigns::Collaborator: read
    Campaign: read
    Team: read
    Membership:
      - read
      - search
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    Client: manage
    Campaigns::Collaborator: manage
    Payment: manage
    Campaign: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcepts::Collaborator: manage
